### ISSUE TITLE
I cannot install any extension

### ISSUE THREAD

**Issue by FerSabGar** [mjakeman/extension-manager#71] opened 2022-01-25 00:06 UTC
Hi. I have a problem with the application. I've installed it as 'system'. It runs well until I try to install any extension since nothing happens after pushing the install button.
 
Starting the application from a terminal, an error is listed which is:
"** (extension-manager:2): CRITICAL **: 01:00:47.977: GDBus.Error:org.gtk.GDBus.UnmappedGError.Quark._g_2dio_2derror_2dquark.Code36: GDBus.Error:org.gnome.Shell.DownloadInfoError: 6"

My system is Ubuntu 20.04.3 LTS with Gnome 3.36.8 under X11

Any ideas?

Thanks a lot and congratulations for this amazing application.

**Comment by FerSabGar** [comment] 2022-01-25 19:01
Solved after installing manually "ca-certificates" .deb file

**Comment by mjakeman** [comment] 2022-01-26 09:49
Given the error is being reported back via DBus, the issue is originating from within gnome-shell. So there's very little we can do app-side in order to fix it. It's already been tracked (and closed) on the `chrome-gnome-shell` bug tracker: https://gitlab.gnome.org/GNOME/chrome-gnome-shell/-/issues/25

However, I don't think users should need to open the terminal in order to see error messages, so that is an area for improvement.

Let's close this in favour of #31.

**Closed by mjakeman** 2022-01-26 09:49 UTC
