### ISSUE TITLE
An unexpected error occurred in Extension Manager...

### ISSUE THREAD

**Issue by eshafferpdx** [mjakeman/extension-manager#446] opened 2023-07-13 19:23 UTC
**Describe the bug**
../src/src/exm-backtrace.c:78 'exm_backtrace_print'
../src/src/main.c:41 'handler'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
../src/src/exm-detail-view.c:550 'exm_detail_view_init'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
../src/src/exm-window.c:437 'exm_window_init'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
../src/src/exm-application.c:61 'get_current_window'
../src/src/exm-application.c:91 'exm_application_activate'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
../src/src/main.c:109 'run_app'
../src/src/main.c:149 'main'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'

**System Information:**
 -Ubuntu 23.04
 - Extension Manager version - app force closes when accessing 'About Extension Manager' menu selection, version unknown via App. Gnome Software Center shows 0.40 version
 - Package format - Snap
**Additional context**
While Extension Manager crashes with the error above, it will successfully launch after opening Extensions app, v44.2, .deb.

**Comment by mjakeman** [comment] 2023-07-14 14:11
Duplicate of #445

I suspect this is also a duplicate of #424

**Closed by mjakeman** 2023-07-14 14:11 UTC
