### ISSUE TITLE
Feature Request: Extension Homepage Button

### ISSUE THREAD

**Issue by cmkohnen** [mjakeman/extension-manager#364] opened 2023-03-30 16:35 UTC
GNOME Extensions provides a link to each extensions home page, often times the upstream repository. It would be nice if extension-manager could display such a button, next to the one leading to the GNOME Extensions page.

**Comment by mjakeman** [comment] 2023-06-15 09:58
Duplicate of #162

**Closed by mjakeman** 2023-06-15 09:58 UTC
