### ISSUE TITLE
Extension manger did not start with the system in Manjaro

### ISSUE THREAD

**Issue by hackroot9623** [mjakeman/extension-manager#730] opened 2024-10-21 12:57 UTC
Support Log
----
Version: 0.5.1
Package Format: Flatpak
Status: Official
OS: GNOME 46 (Flatpak runtime)
GTK: 4.14.5
Libadwaita: 1.5.4
----
../src/exm-backtrace.c:107 'exm_backtrace_print'
../src/main.c:42 'handler'
2 frames omitted
../src/exm-browse-page.c:161 'refresh_search'
5 frames omitted
../src/local/exm-manager.c:778 'on_state_changed'
7 frames omitted
../src/local/shell-dbus-interface.c:2756 'shell_extensions_proxy_g_signal'
11 frames omitted
../src/main.c:110 'run_app'
2 frames omitted
../sysdeps/x86_64/start.S:115 '_start'

**Comment by oscfdezdz** [comment] 2024-10-21 21:33
Duplicate of #398

**Closed by oscfdezdz** 2024-10-21 21:33 UTC
