### ISSUE TITLE
Uh, I disabled extension version validation

### ISSUE THREAD

**Issue by keyhost505** [mjakeman/extension-manager#719] opened 2024-09-26 08:14 UTC
Support Log
----
Version: 0.5.1
Package Format: Flatpak
Status: Official
OS: GNOME 46 (Flatpak runtime)
GTK: 4.14.5
Libadwaita: 1.5.4
----
../src/exm-backtrace.c:107 'exm_backtrace_print'
../src/main.c:42 'handler'
2 frames omitted
../src/exm-comment-dialog.c:144 'on_get_comments'
2 frames omitted
../src/web/exm-request-handler.c:80 'request_callback'
21 frames omitted
../src/main.c:110 'run_app'
2 frames omitted
../sysdeps/x86_64/start.S:115 '_start'

**Comment by oscfdezdz** [comment] 2024-09-26 09:28
Duplicate of #495

**Closed by oscfdezdz** 2024-09-26 09:28 UTC
