### ISSUE TITLE
Unexpected Error

### ISSUE THREAD

**Issue by Jhon98E** [mjakeman/extension-manager#678] opened 2024-06-21 20:10 UTC
Support Log
----
Version: 0.5.1
Package Format: Flatpak
Status: Official
OS: GNOME 46 (Flatpak runtime)
GTK: 4.14.4
Libadwaita: 1.5.1
----
../src/exm-backtrace.c:107 'exm_backtrace_print'
../src/main.c:42 'handler'
41 frames omitted
../src/main.c:110 'run_app'
2 frames omitted
../sysdeps/x86_64/start.S:115 '_start'

**Comment by oscfdezdz** [comment] 2024-06-21 21:45
Duplicate of #644

**Closed by oscfdezdz** 2024-06-21 21:45 UTC
