### ISSUE TITLE
Odd conflict when attempting to install

### ISSUE THREAD

**Issue by grg3** [mjakeman/extension-manager#234] opened 2022-08-06 11:41 UTC
Failed to commit transaction:
conflicting files:
- extension-manager: /usr/share/icons/hicolor/scalable/actions/settings-symbolic.svg already exists in filesystem (owned by cozy-audiobooks)

**Comment by mjakeman** [comment] 2022-08-08 00:23
Duplicate of https://github.com/mjakeman/extension-manager/issues/157

This is a problem with how we (and cozy) handle icons, I haven't had the time to look into it but it seems to affect 'traditional' packages such as those from the AUR. In the mean time I would suggest installing from flathub since it doesn't have this issue.

**Closed by mjakeman** 2022-08-08 00:23 UTC
