### ISSUE TITLE
Flashback problem , in Ubuntu22.04 LTS( Jammy) !

### ISSUE THREAD

**Issue by Juminiy** [mjakeman/extension-manager#213] opened 2022-06-15 09:47 UTC
The extension admin panel can be opened normally, but click Browse to exit immediately, no error report and crash information.
Also, I can not install any extensions except the GSConnect.
My Hardware :
CPU: Intel i7 9750H 
GPU: NVIDIA RTX2060
MotherBoard : Alienware 
The RAM and SSD are not important points.
Wish that someone will help me a lot.

**Comment by mjakeman** [comment] 2022-06-15 12:57
Hi, are you using an HTTP proxy? That is a known issue (#192)

Also could you elaborate on what you mean by Flashback problem?

**Comment by mjakeman** [comment] 2022-07-01 08:04
I'm closing this as a duplicate of #192. Feel free to reopen the issue if this is not the case.

**Closed by mjakeman** 2022-07-01 08:04 UTC

**Comment by Juminiy** [comment] 2022-07-23 03:00
I'm surly to use http and https proxy globally, however I‘m already solve it by installing all the extension manually,thanks for your advice, 谢谢😄!
