### ISSUE TITLE
Crashes! behind system proxy

### ISSUE THREAD

**Issue by CatchMeIUC** [mjakeman/extension-manager#192] opened 2022-05-06 15:57 UTC
I'm using U 22.04 and a VPN app to go out . My system proxy is 127.0.0.1:<port>. I have to use the app + system proxy pair for Internet.

Every time I click Browse, the app crashed with error "Segmentation fault (core dumped)"

Please tell me the solution. Thanks!

**Comment by gapplef** [comment] 2022-06-03 14:59
I have the same problem.

**Comment by elenio72** [comment] 2022-06-06 10:45
Same problem here.

**Comment by mjakeman** [comment] 2022-06-07 22:22
This will be a problem somewhere in the networking code. As I don't have any kind of system proxy to connect to, I'm not able to debug this myself anytime soon.

If someone technically inclined would like to help, the first step would be to generate a backtrace to see where the crash is occurring. Maybe this article can help: https://blogs.gnome.org/mcatanzaro/2021/09/18/creating-quality-backtraces-for-crash-reports/

I'll mark this as "Help Wanted" for now.

**Comment by elenio72** [comment] 2022-06-10 23:15
In order to help, I attach two files with backtraces.
[ex-manager-crash1.log](https://github.com/mjakeman/extension-manager/files/8882663/ex-manager-crash1.log)
[ex-manager-crash2.log](https://github.com/mjakeman/extension-manager/files/8882664/ex-manager-crash2.log)

**Comment by mjakeman** [comment] 2022-06-11 21:30
Hi @elenio72, could you attach the output of the `bt` (backtrace) command when using `gdb`?

The attached backtraces do not include function signatures so I can't tell where the crash occurred, other than that it did occur somewhere in extension-manager.

**Comment by ZCShou** [comment] 2022-06-13 01:08
I have the same problem. When system's proxy is enabled and switching the browse tab, it would crash.

**Comment by elenio72** [comment] 2022-06-15 10:26
> Hi @elenio72, could you attach the output of the `bt` (backtrace) command when using `gdb`?
> 
> The attached backtraces do not include function signatures so I can't tell where the crash occurred, other than that it did occur somewhere in extension-manager.

(gdb) bt
#0  0x00007f1e0990440b in ?? ()
#1  0x00007f1e099144f3 in ?? ()
#2  0x000009c9b0e0f15b in ?? ()
#3  0x0000000000000000 in ?? ()

**Comment by mjakeman** [comment] 2022-06-15 12:59
>```
>(gdb) bt
>#0 0x00007f1e0990440b in ?? ()
>#1 0x00007f1e099144f3 in ?? ()
>#2 0x000009c9b0e0f15b in ?? ()
>#3 0x0000000000000000 in ?? ()
>```

Ah, that means debug symbols are not loaded. I won't be able to narrow it down using that. I'll try get access to a proxy from somewhere, let's aim to have this fixed for the (upcoming) 0.4 release.

**Comment by mjakeman** [comment] 2022-09-24 12:17
I've now pushed Extension Manager 0.4 to Flathub Beta.

It has a built in crash monitor which will generate a report after crashing. Since I don't have access to a proxy, I would appreciate if someone could run the new version and upload the generated backtrace here.

Thanks!

---

You can install 0.4 as follows:

```
# Add flathub-beta
flatpak remote-add --if-not-exists flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo

# Install Extension Manager
flatpak install flathub-beta com.mattjakeman.ExtensionManager
```

It is a good idea to remove flathub-beta and uninstall extension-manager afterwards as it will not be automatically updated when the final release comes out.

The crash window looks like this:

<img width="323" alt="image" src="https://user-images.githubusercontent.com/12368711/192097388-1e67fde4-9da0-4196-8f05-e31c8ce9bf43.png">

**Comment by elenio72** [comment] 2022-09-28 07:29
With 0.4 version the problem is resolved. Now I can browse the extensions available correctly behind enterprise network proxy.
Thanks!

**Comment by mjakeman** [comment] 2022-09-28 08:31
@elenio72 Great to hear! I'll close this issue then, if any other (possibly related) problems pop-up, please open a new issue :)

**Closed by mjakeman** 2022-09-28 08:31 UTC
Labels: bug, help wanted
