### ISSUE TITLE
no error message if can't unzip when installing a new extension

### ISSUE THREAD

**Issue by dbrugan** [mjakeman/extension-manager#755] opened 2024-12-15 02:09 UTC
**Describe the bug**
If the user's OS doesn't have unzip installed as native package, installing a new extension in the "browse" tab will fail, when it fails no error message is displayed to the user unless the app is running from the terminal which shows the message:

`** (extension-manager:3): CRITICAL **: 22:56:24.890: GDBus.Error:org.gnome.Shell.Extensions.Error.ExtractFailed: Failed to execute child process “unzip” (No such file or directory)`

it's expected for the app to show the user a message about what have failed in the installation

**System Information:**
 - Distro: Ubuntu 24.04
 - Extension Manager version: 0.6.0
 - Package format: Flatpak

**Comment by oscfdezdz** [comment] 2024-12-15 10:19
See https://github.com/mjakeman/extension-manager/issues/198#issuecomment-1149240163

**Comment by oscfdezdz** [comment] 2024-12-15 10:19
Duplicate of #198

**Closed by oscfdezdz** 2024-12-15 10:19 UTC
