### ISSUE TITLE
Exention Manager Crashes After Enabling User Themes

### ISSUE THREAD

**Issue by hard1day** [mjakeman/extension-manager#704] opened 2024-08-16 05:20 UTC
**Describe the bug**

so it crashed after i turned on user themes 

Version: 0.5.1
Package Format: Flatpak
Status: Official
OS: GNOME 46 (Flatpak runtime) (fresh install on arch) 
GTK: 4.14.4
Libadwaita: 1.5.3
----
../src/exm-backtrace.c:107 'exm_backtrace_print'
../src/main.c:42 'handler'
41 frames omitted
../src/main.c:110 'run_app'
2 frames omitted
../sysdeps/x86_64/start.S:115 '_start'

**Additional context**

thats it

**Comment by oscfdezdz** [comment] 2024-09-27 11:57
Duplicate of #644

**Closed by oscfdezdz** 2024-09-27 11:57 UTC
