### ISSUE TITLE
An unexpected error occurred while reading an extension's comments

### ISSUE THREAD

**Issue by vitorfg8** [mjakeman/extension-manager#472] opened 2023-08-25 13:09 UTC
**Describe the bug**
App crashed after clicking "Show All Reviews" on an extension

**System Information:**
 - Distro: Fedora
 - Extension Manager version: 0.4.2
 - Package format: Flatpak

**Additional context**

```
Support Log
----
Version: 0.4.2
Development: No
Package Format: Unknown Package
Status: Official
----
../src/exm-backtrace.c:79 'exm_backtrace_print'
../src/main.c:41 'handler'
(null):0 '(null)'
(null):0 '(null)'
../src/exm-comment-dialog.c:139 'on_get_comments'
(null):0 '(null)'
(null):0 '(null)'
../src/web/exm-request-handler.c:80 'request_callback'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
../src/main.c:109 'run_app'
(null):0 '(null)'
(null):0 '(null)'
../sysdeps/x86_64/start.S:115 '(null)'
(null):0 '(null)'
```

**Comment by mjakeman** [comment] 2024-06-05 14:57
Let's track it in #495

Duplicate of #495

**Closed by mjakeman** 2024-06-05 14:57 UTC
Labels: bug
