### ISSUE TITLE
Extension manager Could not check for updates

### ISSUE THREAD

**Issue by kinolex** [mjakeman/extension-manager#497] opened 2023-10-18 08:03 UTC
*System Information:**
 - zorin os lite 
 - Extension Manager version (e.g. 0.4.2)
    Flatpak

**Comment by oscfdezdz** [comment] 2023-10-18 09:07
Hi, Zorin OS Lite uses XFCE as desktop environment not GNOME, have you manually installed it?

**Comment by oscfdezdz** [comment] 2023-10-18 09:25
Hi, Zorin OS Lite uses XFCE as desktop environment by default not GNOME, have you manually install it?

**Comment by oscfdezdz** [comment] 2024-03-16 15:05
Duplicate of #452 as both distributions share default desktop environment.

**Closed by oscfdezdz** 2024-03-16 15:05 UTC
Labels: needs info
