### ISSUE TITLE
An Unexpected error occurered in Extenstion manager while opening ... showing all the extensions unsupported

### ISSUE THREAD

**Issue by HardikLovesTech** [mjakeman/extension-manager#750] opened 2024-11-28 19:59 UTC
**BUG**
Could not check for updates: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name :1.346 was not provided by any .service files

**System Information:**
 - Linux Mint 22 Cinnamon
 - Version: 0.5.1
 Package Format: Flatpak
 Status: Official
 OS: GNOME 46 (Flatpak runtime)
 GTK: 4.14.5
 Libadwaita: 1.5.5
 -Flatpack

Everytime I open the manager the user extension button gets turned off automatically
also all the extensions are showing unsupported
![Screenshot from 2024-11-29 01-28-15](https://github.com/user-attachments/assets/0c257a93-b05f-4ab4-9560-8eca284050c4)
![image](https://github.com/user-attachments/assets/42d4341f-62b2-4fa4-b666-1e741459e5c1)
![image](https://github.com/user-attachments/assets/901439ab-b06a-48f2-962a-977515487347)

**Comment by oscfdezdz** [comment] 2024-11-28 20:02
See https://github.com/mjakeman/extension-manager/issues/323#issuecomment-2150187701

**Comment by oscfdezdz** [comment] 2024-11-28 20:02
Duplicate of #323

**Closed by oscfdezdz** 2024-11-28 20:02 UTC
