### ISSUE TITLE
Error on first run on Ubuntu 22.04

### ISSUE THREAD

**Issue by davehodson** [mjakeman/extension-manager#322] opened 2022-12-10 12:23 UTC
Could not check for updates: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.105" (uid=1000 pid=5429 comm="/snap/gnome-extension-manager/10/usr/bin/extension" label="snap.gnome-extension-manager.gnome-extension-manager (enforce)") interface="org.gnome.Shell.Extensions" member="CheckForUpdates" error name="(unset)" requested_reply="0" destination=":1.106" (uid=1000 pid=5437 comm="/usr/bin/gjs /usr/share/gnome-shell/org.gnome.Shel" label="unconfined")

**Comment by mjakeman** [comment] 2022-12-11 06:56
Duplicate of #319 

At the moment, there's no official snap package for Extension Manager. Please report this to the maintainer of the snap package.

I'd recommend using the flatpak in the mean time as that's known to work on Ubuntu 22.04.

**Closed by mjakeman** 2022-12-11 06:56 UTC
Labels: third-party
