### ISSUE TITLE
Extension with missing title

### ISSUE THREAD

**Issue by leoheck** [mjakeman/extension-manager#179] opened 2022-04-18 14:35 UTC
There is an extension that does not have a Title. Is this a bug in the extension itself or with the Extension Manager?
If the Extensions does not have an important field, I can file a bug report there. 
![image](https://user-images.githubusercontent.com/1277920/163823526-1c772d18-d207-4971-9921-b21f6fcc0060.png)

**Comment by mjakeman** [comment] 2022-04-18 16:16
Duplicate of #173 which was fixed in #175 

Will be included in the next minor update :)

**Closed by mjakeman** 2022-04-18 16:16 UTC

**Comment by leoheck** [comment] 2022-04-18 18:09
Ah, nice. Thank you for the feedback @mjakeman
