### ISSUE TITLE
"Sound Input & Output Device Chooser" shows empty title

### ISSUE THREAD

**Issue by demolg** [mjakeman/extension-manager#185] opened 2022-04-24 15:57 UTC
![Screenshot from 2022-04-24 23-49-01](https://user-images.githubusercontent.com/26198098/164985041-5f3834c0-45a2-47b1-accc-76d7c6ba82c6.png)

I change character "&" to "and", then the title get shown.

**Comment by mjakeman** [comment] 2022-04-24 20:25
Duplicate of #173 and fixed in #175

Will be fixed by version 0.3.1 which is mostly ready to go, just needs to be tagged and tested.

**Closed** 2022-04-24 20:25 UTC
