### ISSUE TITLE
New Bug

### ISSUE THREAD

**Issue by RafayKhan177** [mjakeman/extension-manager#440] opened 2023-07-07 09:13 UTC
Support Log
----
Version: 0.4.2
Development: No
Package Format: Unknown Package
Status: Official
----
../src/exm-backtrace.c:79 'exm_backtrace_print'
../src/main.c:41 'handler'
(null):0 '(null)'
(null):0 '(null)'
../src/exm-browse-page.c:162 'refresh_search'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
../src/local/exm-manager.c:772 'on_state_changed'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
../src/local/shell-dbus-interface.c:2756 'shell_extensions_proxy_g_signal'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
../src/main.c:109 'run_app'
(null):0 '(null)'
(null):0 '(null)'
../sysdeps/x86_64/start.S:115 '(null)'
(null):0 '(null)'

**Comment by mjakeman** [comment] 2023-07-07 09:40
>  ../src/local/shell-dbus-interface.c:2756 'shell_extensions_proxy_g_signal'

Bizarre, I've never seen this before

What is your:
 - Operating System
 - Package Format (e.g. Flatpak)

**Comment by mjakeman** [comment] 2023-07-15 22:28
Probably a duplicate of #398

**Closed by mjakeman** 2023-07-15 22:28 UTC
Labels: bug, needs info
