### ISSUE TITLE
Crash under dell-ubuntu 20.04

### ISSUE THREAD

**Issue by Vildnex** [mjakeman/extension-manager#444] opened 2023-07-11 16:50 UTC
**Describe the bug**
I've installed extension-manager via the fallowing command:

`sudo snap install gnome-extension-manager`

After the installation was successful I've tried to open it and I get the fallowing error:
```
../src/src/exm-backtrace.c:78 'exm_backtrace_print'
../src/src/main.c:41 'handler'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
../src/src/exm-application.c:61 'get_current_window'
../src/src/exm-application.c:91 'exm_application_activate'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
../src/src/main.c:109 'run_app'
../src/src/main.c:149 'main'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'

```
Also, some time in the fewer occasions when it did work and I could open the program, I did not find any extension and after few seconds I will get another crash with this error message in terminal:

`/snap/gnome-extension-manager/10/usr/bin/extension-manager: symbol lookup error: /snap/gnome-extension-manager/10/gnome-platform/usr/lib/x86_64-linux-gnu/libadwaita-1.so.0: undefined symbol: gtk_widget_dispose_template
`

I am not sure what should I do or if I did something wrong, or this is a bug?

**System Information:**
 - Distro: **Ubuntu 20.04.6 LTS**
 - Extension Manager version: **0.4.0**
 - Package format: **snap**

**Comment by mjakeman** [comment] 2023-07-14 14:07
Seems like a duplicate of #424 

I think a recent Ubuntu update has broken the snap package. I don't have an environment to test this at the moment either unfortunately. Thanks for the report however.

For now, I would recommend the flatpak version of the app as this doesn't seem to have any of the problems.

**Closed by mjakeman** 2023-07-14 14:07 UTC
