### ISSUE TITLE
Can't install extensions if unzip is not installed

### ISSUE THREAD

**Issue by miguel-furtado** [mjakeman/extension-manager#732] opened 2024-10-30 23:46 UTC
**Describe the bug**

If unzip is not installed on the host (which seems to be the default in some distros) when you try to install some extension you get this log

```
** (extension-manager:3): CRITICAL **: 23:34:56.686: GDBus.Error:org.gnome.Shell.Extensions.Error.ExtractFailed: Failed to execute child process “unzip” (No such file or directory)
```

No error message is shown in the ui at all, the install button is still there but clicking it has no effect.

I didn't expect to have to install a dependency on the host since the flatpak is sandboxed but maybe I'm misunderstanding how this works.

**System Information:**
 - Distro (Ubuntu 24.10)
 - Extension Manager version (0.5.1)
 - Package format (Flatpak)

**Comment by oscfdezdz** [comment] 2024-10-31 09:54
See https://github.com/mjakeman/extension-manager/issues/198#issuecomment-1149240163

**Comment by oscfdezdz** [comment] 2024-10-31 16:05
Duplicate of #198

**Closed by oscfdezdz** 2024-10-31 16:05 UTC
