### ISSUE TITLE
extensions not updating automatically (kinda)

### ISSUE THREAD

**Issue by allaeddineomc** [mjakeman/extension-manager#236] opened 2022-08-09 00:44 UTC
the extensions doesn't update automatically unless the traditional extensions app is present , it would be really great if extension manager could update extensions without relaying on "extensions" app

**Comment by mjakeman** [comment] 2022-08-09 01:19
Already tracked and (kinda) fixed :)

Extension Manager is supported by GNOME Shell as of the latest version of GNOME 42 (might not be packaged for distros yet) and the upcoming GNOME 43. We still need to find a solution for GNOME 41 and below, but I'm not so worried about those going forward.

Duplicate of #165

**Closed by mjakeman** 2022-08-09 01:19 UTC
