### ISSUE TITLE
unable to use 

### ISSUE THREAD

**Issue by venomshiva** [mjakeman/extension-manager#353] opened 2023-03-16 07:16 UTC
pls help me to get out of it i got frusturated after this problem

Could not check for updates: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.420" (uid=1000 pid=29851 comm="/snap/gnome-extension-manager/10/usr/bin/extension" label="snap.gnome-extension-manager.gnome-extension-manager (enforce)") interface="org.gnome.Shell.Extensions" member="CheckForUpdates" error name="(unset)" requested_reply="0" destination=":1.421" (uid=1000 pid=29886 comm="/usr/bin/gjs /usr/share/gnome-shell/org.gnome.Shel" label="unconfined")

**Comment by bouchedid** [comment] 2023-03-21 08:43
Same issue on Ubuntu 22.04.2 - Gnome 42.5

**Comment by mjakeman** [comment] 2023-03-21 11:12
Duplicate of #349, #347, and #341

The unofficial snap package is broken. Please use the official [flatpak](https://beta.flathub.org/apps/details/com.mattjakeman.ExtensionManager) package instead.

I will be taking over maintainership of the snap when I have some time, but in the mean time I suggest using the flatpak.

**Closed by mjakeman** 2023-03-21 11:12 UTC
