### ISSUE TITLE
Snap version of this app

### ISSUE THREAD

**Issue by soumyatheman** [mjakeman/extension-manager#124] opened 2022-03-17 16:33 UTC
I know that most of the people here hate snaps, but at least in my eyes, snaps are better. Because they can be installed in any device including servers, Iots etc. So I would request you to create a snap version of this also. There is also a documentation of snaps by canonical, if u need. Thanks in advance.

**Comment by rafal06** [comment] 2022-03-17 19:15
1. Flatpaks can also be installed on everything and they don't even depend on systemd in opposite to snaps.
2. Why would you want to install Extension Manager on a server or IoT device anyway?
3. Flatpak don't have proprietary backend in opposite to snap.

**Comment by mjakeman** [comment] 2022-03-18 03:03
Snap support is planned down the line, since it's the default format on Ubuntu. My immediate focus however is on releasing 0.3 (updating, error handling, reviews) in time for GNOME 42.

Closing as duplicate of #117

**Closed by mjakeman** 2022-03-18 03:03 UTC
Labels: duplicate
