### ISSUE TITLE
Touch-pad Gesture's Bug

### ISSUE THREAD

**Issue by oyajun** [mjakeman/extension-manager#201] opened 2022-05-29 02:21 UTC
You can back page using touch-pad gesture on title bar.
![ok](https://user-images.githubusercontent.com/81346541/170849307-33ab264c-1535-470b-907f-d37471ebc287.png)

However, you cannot do it on other place.
![Screenshot from 2022-05-29 11-16-59](https://user-images.githubusercontent.com/81346541/170849319-ca76fe15-1177-4093-8c36-941fce307c4c.png)

**Comment by mjakeman** [comment] 2022-05-29 05:48
Duplicate of #161

Due to the way GTK handles scrolled windows, if you start a swipe inside a scrollable area, the swipe cannot propagate to any parent containers (i.e. the leaflet which gives us the stacked view). See https://github.com/mjakeman/extension-manager/issues/161#issuecomment-1092427470 for a bit more info - we'll get this for free when it's fixed upstream.

**Closed by mjakeman** 2022-05-29 05:48 UTC
