### ISSUE TITLE
Crash occured when acquiring comment of an extension.

### ISSUE THREAD

**Issue by liboqiao1234** [mjakeman/extension-manager#756] opened 2024-12-15 11:09 UTC
Support Log
----
Version: 0.6.0
Package Format: Flatpak
Status: Official
OS: GNOME 47 (Flatpak runtime)
GTK: 4.16.7
Libadwaita: 1.6.2
----
../src/exm-backtrace.c:108 'exm_backtrace_print'
../src/main.c:44 'handler'
2 frames omitted
../src/exm-comment-dialog.c:173 'on_get_comments'
2 frames omitted
../src/web/exm-request-handler.c:85 'request_callback'
21 frames omitted
../src/main.c:112 'run_app'
2 frames omitted
../sysdeps/x86_64/start.S:115 '_start'

**Comment by oscfdezdz** [comment] 2024-12-20 22:28
It looks like the backtrace is the same as in #495, let's follow this there.

**Comment by oscfdezdz** [comment] 2024-12-20 22:28
Duplicate of #495

**Closed by oscfdezdz** 2024-12-20 22:28 UTC
