### ISSUE TITLE
erroe message when closing all extentions 

### ISSUE THREAD

**Issue by samarth-nagar** [mjakeman/extension-manager#552] opened 2024-01-10 14:10 UTC
**Describe the bug**
when dissabling all extentions this error comes 

**System Information:**
 - Fedora
 - 45 
 - flatpak

**Additional context**
../src/exm-backtrace.c:92 'exm_backtrace_print'
../src/main.c:41 'handler'
(null):0 '(null)'
(null):0 '(null)'
../src/exm-browse-page.c:159 'refresh_search'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
../src/local/exm-manager.c:772 'on_state_changed'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
../src/local/shell-dbus-interface.c:2756 'shell_extensions_proxy_g_signal'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
(null):0 '(null)'
../src/main.c:109 'run_app'
(null):0 '(null)'
(null):0 '(null)'
../sysdeps/x86_64/start.S:115 '_start'
(null):0 '(null)'

**Comment by oscfdezdz** [comment] 2024-01-21 10:26
Hi, does the same thing happen with the Extensions app? I use the same distribution and version of Extensions Manager in Flatpak and I can't reproduce it.

**Comment by samarth-nagar** [comment] 2024-01-26 19:31
@oscfdezdz thanks for reaching out it seems like that was once aa blue moon bug which i cant recreate myself

**Comment by oscfdezdz** [comment] 2024-01-27 10:37
Closing this issue then, feel free to reopen it if it happens again.

**Closed by oscfdezdz** 2024-01-27 10:37 UTC
Labels: bug, needs info
