### ISSUE TITLE
gnome extension manager search not working 

### ISSUE THREAD

**Issue by MohammedKhayat-dev** [mjakeman/extension-manager#694] opened 2024-07-25 13:33 UTC
![Screenshot from 2024-07-25 09-33-22](https://github.com/user-attachments/assets/ead4099b-7d5b-445e-af2b-0d59bb5d64ee)
**Describe the bug**
A description of the bug goes here.

**System Information:**
 - Distro (e.g. Fedora, Ubuntu)
 - Extension Manager version (e.g. 0.5.1)
 - Package format (Flatpak, Snap, other)

**Additional context**

**Comment by oscfdezdz** [comment] 2024-07-25 13:36
GNOME Extensions website is experiencing a major outage, see https://status.gnome.org/.

**Comment by oscfdezdz** [comment] 2024-07-25 13:36
Duplicate of #672

**Closed by oscfdezdz** 2024-07-25 13:36 UTC
