### ISSUE TITLE
Search results are incomplete

### ISSUE THREAD

**Issue by timrichardson** [mjakeman/extension-manager#158] opened 2022-03-29 05:28 UTC
In the current version (0.3.0) a search for the string
windows

does not find the extension
Auto Move Windows

screen shot: https://imgur.com/QGYRPeN

https://imgur.com/2VNhYWt

**Comment by mjakeman** [comment] 2022-03-29 11:16
This is working as intended - Extension Manager only displays the top 10 results for each query (based on whichever criteria is being used: Popularity, Recent, etc). So "Auto Move Windows" is more popular compared for extensions containing "Auto" than those containing "Windows".

This issue would be fixed by showing more than 10 results, although that would require a rethink of how we obtain search results from [extensions-web](https://extensions.gnome.org/).

**Comment by timrichardson** [comment] 2022-03-29 21:20
Thanks, that makes sense, but it is a bit surprising. There is no hint there are possible search results not yet shown. You could say "only top 10 results shown" for instance, it would be helpful. A relatively simple temporary solution to showing further results could be a link to the relevant search page on extensions-web since there is no other way to discover the overflow extensions. 

 Also if only ten are to be shown, perhaps unsupported extensions can be optionally filtered out to improve the relevance of those ten results. I will make a new issue about that.

**Comment by mjakeman** [comment] 2022-03-31 06:54
> Also if only ten are to be shown, perhaps unsupported extensions can be optionally filtered out to improve the relevance of those ten results. I will make a new issue about that if you think this is a valid feature. You may not want to over-clutter the elegant UI.

Filtering out unsupported extensions is definitely something I'd like to have - it's currently tracked on #114. 

> Thanks, that makes sense, but it is a bit surprising.

Agreed - it's not great for discoverability. Long term, I'd like something along the lines of a 'show more results' button, which loads the next 10 results (and so on).
 
> If you think any of these ideas are acceptable, I will work on them if you wish.

Contributions are very welcome! - I'm happy to review any PRs.

(Was that pull request supposed to be on this repo?)

Regarding the label, I think I'd like to avoid it, since it feels like a crutch for a missing feature. Also, I've promised no changes to translation strings until 0.4, and I'll hopefully have pagination done by then anyway, so it's unlikely to make it into a release.

**Comment by mjakeman** [comment] 2022-05-27 08:06
Let's use #191 to track adding pagination and #114 for toggling unsupported extensions.

**Closed by mjakeman** 2022-05-27 08:06 UTC
Labels: enhancement, help wanted
