### ISSUE TITLE
Blank window, GLib-GObject-CRITICAL

### ISSUE THREAD

**Issue by shawazi** [mjakeman/extension-manager#710] opened 2024-09-05 01:17 UTC
**Describe the bug**
A description of the bug goes here.
![Screenshot from 2024-09-04 20-58-41](https://github.com/user-attachments/assets/8cdb78d3-c379-40de-b24b-05468eea20c7)

Blank window even after reinstallation. 

**System Information:**
 - Distro (e.g. Fedora, Ubuntu)
 - Extension Manager version (e.g. 0.5.1)
 - Package format (Flatpak, Snap, other)

Arch, AUR package

**Additional context**
`{09:16:51 shawaz@archpc ~}$ extension-manager

(extension-manager:76046): Gtk-CRITICAL **: 21:16:59.940: Error building template class 'ExmWindow' for an instance of type 'ExmWindow': .:0:0 Invalid object type 'ExmInstalledPage'

(extension-manager:76046): GLib-GObject-CRITICAL **: 21:17:00.145: g_object_set: assertion 'G_IS_OBJECT (object)' failed

(extension-manager:76046): GLib-GObject-CRITICAL **: 21:17:00.145: g_object_set: assertion 'G_IS_OBJECT (object)' failed

(extension-manager:76046): GLib-GObject-CRITICAL **: 21:17:00.145: g_object_set: assertion 'G_IS_OBJECT (object)' failed

(extension-manager:76046): GLib-GObject-CRITICAL **: 21:17:00.145: g_object_bind_property_full: assertion 'G_IS_OBJECT (target)' failed
{09:17:03 shawaz@archpc ~}$ `

**Comment by oscfdezdz** [comment] 2024-09-05 07:53
See https://github.com/mjakeman/extension-manager/issues/709#issuecomment-2323261308

**Comment by oscfdezdz** [comment] 2024-09-05 07:54
Duplicate of #709

**Closed by oscfdezdz** 2024-09-05 07:54 UTC
Labels: duplicate
