### ISSUE TITLE
Updating needs the 'GNOME Extensions' app on GNOME 40

### ISSUE THREAD

**Issue by CharoSW** [mjakeman/extension-manager#165] opened 2022-04-02 03:22 UTC
I had a situation where i opened the app knowing there was an update for Just Perfection.  However nothing seemed to happened, no sign of the update at all.  I closed and reopened the app a few times to try and trigger an update check but again nothing happened.  I then installed the official extensions app and that immediately seemed to get the update.  Now i am not quite sure if the app hadn't triggered the check properly or even what need to happen for a check to occur but a way that i can manually check for updates would have been useful here

**Comment by mjakeman** [comment] 2022-04-08 04:32
That's odd :thinking:

As of 0.3, the app checks for updates whenever a window is opened.

Which version on the app were you using? Could you also provide your distro and where you got the app from?

**Comment by d0vi** [comment] 2022-04-09 16:56
Hello @mjakeman, I am using _Extension Manager_ and I think it is a great application for managing my extensions, so thank you so much for your work.

Just to add to this issue, I am experiencing the same problem. Two of my extensions released new versions these past days, but I did not have any chance to update them from inside the app:
- _Burn My Windows_ is three versions behind.
- _Blur my Shell_ is two versions behind.

These updates were released after I installed the `v0.3` of Extension Manager.
To complement this information, I am using Fedora Workstation 36 Beta on a virtual machine running on VirtualBox.

**Comment by bdaase** [comment] 2022-04-16 18:40
@mjakeman Well, I can confirm that updating does not work on Fedora 36 (GNOME 42) for me as well. I think, however, that this an underlying problem in GNOME and has nothing to do with this extension. In previous GNOME versions I was able to update my extensions via `/usr/bin/gdbus call --session --dest org.gnome.Shell.Extensions --object-path /org/gnome/Shell/Extensions --method org.gnome.Shell.Extensions.CheckForUpdates` on the CLI, which also does not work anymore in GNOME 42, and I expect this app to call something similar along these lines.

**Comment by rafal06** [comment] 2022-04-16 20:51
It doesn't work for me, either (Fedora 35, Gnome 41.4)

**Comment by philn** [comment] 2022-04-17 17:06
I filed an issue, https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/5360

**Comment by philn** [comment] 2022-04-17 17:56
This might be a bug here in the end... As mentioned in that gnome-shell ticket, I re-installed org.gnome.Extensions and was notified of the pending updates.

**Comment by mjakeman** [comment] 2022-04-18 01:23
Thanks @philn and @bdaase for looking into this.

From what I gather, the issue is that GNOME Shell only permits the DBus call if the org.gnome.Extensions app is installed, regardless of who the caller is (see [extensionSystem.js#L66](https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/29263fd6dcad19c299dee0c1bb47f3c8116d837c/js/ui/extensionSystem.js#L66)). Since I also have the official app installed, this wouldn't have shown up in my testing.

I'm going to look further into how `chrome-gnome-shell` (the browser extension) handles this, as that seems to do updates fine. If it turns out we're blocked on GNOME Shell, then I'll open an issue and see if we can have the check dropped for explicit calls to the DBus API.

**Comment by weavermarquez** [comment] 2022-05-11 15:47
Hi there - if upgrades cannot be done unless org.gnome.Extensions is installed, could you please include some form of documentation in either the README or elsewhere, for us Fedora + Fedora Silverblue users? The Extensions does not come installed by default, and for Silverblue, we want to minimize our overlaid apps, and I had been so confused I had to manually uninstall and reinstall the extensions to get an upgrade after I saw "automatic updates" in the release notes.

**Comment by mjakeman** [comment] 2022-05-16 02:01
@weavermarquez I agree - I've added a "Known Issues" section to the README. I'll also include it in the release notes for 0.3.1.

This is at the top of my list since it's a pretty major flaw - it'll need changes to GNOME Shell to resolve however, so it might be with us long term.

I'm looking at adding an in-app warning for older GNOME versions to work around this.

**Comment by onlyreportingissues** [comment] 2022-05-26 11:09
I'm getting confused. Which one is necessary to get automatic updates? gnome-extensions-app (rpm, not flatpak) or org.gnome.Extensions (flatpak)?

**Comment by mjakeman** [comment] 2022-06-07 22:07
I've opened https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/5564 upstream.

From a discussion on [#extensions:gnome.org](https://matrix.to/#/#extensions:gnome.org), one solution is to create an extension manager "integrations" plugin which is itself hosted on EGO. This would patch out the check for the official extensions app and could also let us support things like Lists (#75). The user would be prompted to install this from the installed extensions view.

Tentatively, let's support GNOME 3.38 and later? (debian bullseye)

**Comment by mjakeman** [comment] 2022-06-09 11:17
Hi everyone, I've created a small extension which patches out the check for org.gnome.Extensions in #211, allowing updates to work without the official app - It will be bundled with Extension Manager 0.4 as a one-click install for users.

As this modifies existing GNOME Shell code, I'm wary of conflicts with popular extensions. This is pretty unlikely, since it performs a very specific and minor change, but it still needs to be thoroughly tested before being shipped to end users.

Any help with testing/reporting issues would be much appreciated!

You can try it out by downloading the code from #211, renaming the plugins subdirectory to `extension-manager-utils@mattjakeman.com`, and copying it to `~/.local/share/gnome-shell/extensions`.

**Comment by mjakeman** [comment] 2022-07-03 11:33
Unfortunately this approach is not going to work. GNOME Shell checks for the extensions app both when checking for updates (which this plugin patches) but also when installing updates. As the installation occurs before the extension hook, we cannot patch early enough to make the installation succeed.

I've created an MR for GNOME Shell to add alternate support for Extension Manager, which means this will hopefully be fixed for GNOME 43 and later. In the mean time let's explore other ideas for fixing this on GNOME 3.38-42.

**Comment by d0vi** [comment] 2022-07-03 13:42
Thank you for taking your time investigating this issue, @mjakeman ❤️ 
For those who want to keep an eye on the aforementioned MR in GNOME Shell, here it is: https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/2358.
Cheers!

**Comment by mjakeman** [comment] 2022-07-14 08:14
Extension Manager is now natively supported by GNOME 43 (and above).

Let's use this issue to try and find a fix or workaround for older and current GNOME versions, specifically 3.38-42.

**Comment by alexsch01** [comment] 2022-07-22 13:39
> Extension Manager is now natively supported by GNOME 43 (and above).
> 
> Let's use this issue to try and find a fix or workaround for older and current GNOME versions, specifically 3.38-42.

Nice! I think this change is backported to GNOME 42: https://github.com/GNOME/gnome-shell/commits/gnome-42

**Comment by alexsch01** [comment] 2022-08-11 14:09
@mjakeman Haha nice, you will have to change the title of this issue again!
https://gitlab.gnome.org/GNOME/gnome-shell/-/commit/542101e8b51f55f2845ad6745e0b89ce7ce02196

**Comment by mjakeman** [comment] 2022-08-11 14:32
> Haha nice, you will have to change the title of this issue again!

I love when issues solve themselves :P

Great to see the patch sneak into GNOME 41, this means Extension Manager should work out of the box on all supported versions of GNOME.

I'm considering calling this fixed rather than trying to add any special workarounds for 3.38 and 40. Regarding...
 - GNOME 3.38: I don't think there is any currently maintained distro which ships both 3.38 and gtk4 (and Debian Buster should be reaching end of life around now anyway) which means I wouldn't expect Extension Manager to support it.
 - GNOME 40: This one is a bit more problematic, but we're helped by the fact Ubuntu did not ship it in an LTS release. I think it is reasonable to ask that, as [GNOME 40 is now EOL](https://discourse.gnome.org/t/gnome-40-9-released/9248), users install the official GNOME Extensions app to have updating support. If there are any notable cases of distros still shipping GNOME 40, we could ask them nicely to backport the patch.

Thoughts?

**Comment by mjakeman** [comment] 2022-08-17 09:04
Closing - I've written up [this wiki page](https://github.com/mjakeman/extension-manager/wiki/Known-Issue:-Updates) to summarise the information in this issue. I'll update the README to link to it.

**Closed by mjakeman** 2022-08-17 09:04 UTC
Labels: bug

**Comment by allaeddineomc** [comment] 2022-08-18 10:16
i'm on gnome 42 and the latest release from flathub and the automatic extension updates aren't working unless i install the old extensions app, any solution ?
