### ISSUE TITLE
run_app crash

### ISSUE THREAD

**Issue by ericzlmd** [mjakeman/extension-manager#674] opened 2024-06-18 03:10 UTC
Support Log
----
Version: 0.5.1
Package Format: Flatpak
Status: Official
OS: GNOME 46 (Flatpak runtime)
GTK: 4.14.4
Libadwaita: 1.5.1
----
../src/exm-backtrace.c:107 'exm_backtrace_print'
../src/main.c:42 'handler'
42 frames omitted
../src/main.c:110 'run_app'
2 frames omitted
../sysdeps/x86_64/start.S:115 '_start'

**Comment by oscfdezdz** [comment] 2024-06-18 06:49
Duplicate of #644

**Closed by oscfdezdz** 2024-06-18 06:49 UTC
